steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/metrics:${SHORT_SHA}', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ["push", "gcr.io/$PROJECT_ID/metrics"]
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'metrics', '--image', 'gcr.io/$PROJECT_ID/metrics:${SHORT_SHA}', '--region', 'us-central1', '--platform', 'managed', --port, '80', '--allow-unauthenticated']
